variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

default:
  image: maven:3.6-adoptopenjdk-14-openj9
  cache:
    key: maven-cache
    paths:
      - .m2/repository

test:
  script: |
    apt-get update
    apt-get install -y xvfb
    mvn verify