@startuml
component common {
	package gazelle.auth
	package gazelle.model
}

component jakarta.persistence {
}

common ..> jakarta.persistence

component gazelle{

}

component vue {

}

gazelle ..> vue


component server{
	package gazelle.server.endpoint
	package gazelle.server.error
	package gazelle.server.repository
}

component spring {
        component spring.boot{
        }
}

component h2database {
}

spring ..> h2database

server ..> gazelle.auth
server ..> gazelle.model

server ..> spring

@enduml