@startuml
component common {
	package gazelle.model
	package gazelle.api
}

component jakarta.persistence {
}

common ..> jakarta.persistence

component jackson {
}

common ..> jackson

component gazelleFX{
    package gazelle.ui
	package gazelle.client
}

component gazelle{
    package components
	package router
	package store
	package views
	package client
}

component vue{
}

component axios{
}

gazelle --> vue
client --> axios

server -[hidden]--- gazelle

component jersey{
}

gazelle.ui ..> gazelle.api
gazelle.client ..> gazelle.api
gazelle.client ..> jersey

component javafx {
	component fxml {
	}
}

gazelle.ui ..> javafx

component server{
	package gazelle.server.endpoint
	package gazelle.server.error
	package gazelle.server.repository
	package gazelle.server.service
}


component spring {
        component spring.boot{
        }
}

component h2database {
}

spring ..> h2database

server ..> gazelle.api
server ..> gazelle.model

server ...> spring

@enduml
